### ISSUE TITLE
Views: making the logo

### ISSUE THREAD

**Issue by hayleyarodgers** [hayleyarodgers/pawfect-match#23]

**Comment by AJoanBell** [comment]
Logo variations and colour palette finalise
![2](https://user-images.githubusercontent.com/36496885/185364186-eead5821-751f-47c1-9c58-085980516775.png)
![3](https://user-images.githubusercontent.com/36496885/185364190-42acc33f-eecf-44b6-9ec7-f7e836b11326.png)
![4](https://user-images.githubusercontent.com/36496885/185364194-179910c8-cbf8-40b8-8829-4b8fe59b4e45.png)
![5](https://user-images.githubusercontent.com/36496885/185364197-dcc4df79-7ce3-46f7-8783-d53a4bf0ab49.png)
<img width="929" alt="pawfect_match_hexcolours" src="https://user-images.githubusercontent.com/36496885/185364329-4814d96e-4080-45f8-ad30-cd222cc3873d.png">
d
